// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `wisefuseRpc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "wisefuseRpc.h"
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RPCWiseFuse__WiseFusionInf__geneThumbImg_name = "geneThumbImg";

const ::std::string __RPCWiseFuse__WiseFusionInf__fuseSyn_name = "fuseSyn";

const ::std::string __RPCWiseFuse__WiseFusionInf__fuseAsyn_name = "fuseAsyn";

const ::std::string __RPCWiseFuse__WiseFusionInf__askProcess_name = "askProcess";

const ::std::string __RPCWiseFuse__WiseFusionInf__fetchFuseRes_name = "fetchFuseRes";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RPCWiseFuse::upCast(::IceProxy::RPCWiseFuse::WiseFusionInf* p) { return p; }

void
::IceProxy::RPCWiseFuse::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RPCWiseFuse::WiseFusionInf>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RPCWiseFuse::WiseFusionInf;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::RPCWiseFuse::WiseFusionInf::geneThumbImg(const ::std::string& __p_inPath, const ::std::string& __p_outPath, const ::std::string& __p_bandlist, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RPCWiseFuse__WiseFusionInf__geneThumbImg_name);
    ::IceInternal::Outgoing __og(this, __RPCWiseFuse__WiseFusionInf__geneThumbImg_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_inPath);
        __os->write(__p_outPath);
        __os->write(__p_bandlist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    bool __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::begin_geneThumbImg(const ::std::string& __p_inPath, const ::std::string& __p_outPath, const ::std::string& __p_bandlist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCWiseFuse__WiseFusionInf__geneThumbImg_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCWiseFuse__WiseFusionInf__geneThumbImg_name, __del, __cookie);
    try
    {
        __result->prepare(__RPCWiseFuse__WiseFusionInf__geneThumbImg_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_inPath);
        __os->write(__p_outPath);
        __os->write(__p_bandlist);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::__begin_geneThumbImg(const ::std::string& __p_inPath, const ::std::string& __p_outPath, const ::std::string& __p_bandlist, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RPCWiseFuse::WiseFusionInfPrx __proxy = ::RPCWiseFuse::WiseFusionInfPrx::uncheckedCast(__result->getProxy());
            bool __ret;
            try
            {
                __ret = __proxy->end_geneThumbImg(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (bool)> _response;
    };
    return begin_geneThumbImg(__p_inPath, __p_outPath, __p_bandlist, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

bool
IceProxy::RPCWiseFuse::WiseFusionInf::end_geneThumbImg(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCWiseFuse__WiseFusionInf__geneThumbImg_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

::RPCWiseFuse::FusionInf
IceProxy::RPCWiseFuse::WiseFusionInf::fuseSyn(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RPCWiseFuse__WiseFusionInf__fuseSyn_name);
    ::IceInternal::Outgoing __og(this, __RPCWiseFuse__WiseFusionInf__fuseSyn_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArgs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::RPCWiseFuse::FusionInf __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::begin_fuseSyn(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCWiseFuse__WiseFusionInf__fuseSyn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCWiseFuse__WiseFusionInf__fuseSyn_name, __del, __cookie);
    try
    {
        __result->prepare(__RPCWiseFuse__WiseFusionInf__fuseSyn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArgs);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::__begin_fuseSyn(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RPCWiseFuse::FusionInf&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RPCWiseFuse::FusionInf&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RPCWiseFuse::WiseFusionInfPrx __proxy = ::RPCWiseFuse::WiseFusionInfPrx::uncheckedCast(__result->getProxy());
            ::RPCWiseFuse::FusionInf __ret;
            try
            {
                __ret = __proxy->end_fuseSyn(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::RPCWiseFuse::FusionInf&)> _response;
    };
    return begin_fuseSyn(__p_mapArgs, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::RPCWiseFuse::FusionInf
IceProxy::RPCWiseFuse::WiseFusionInf::end_fuseSyn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCWiseFuse__WiseFusionInf__fuseSyn_name);
    ::RPCWiseFuse::FusionInf __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

::Ice::Int
IceProxy::RPCWiseFuse::WiseFusionInf::fuseAsyn(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RPCWiseFuse__WiseFusionInf__fuseAsyn_name);
    ::IceInternal::Outgoing __og(this, __RPCWiseFuse__WiseFusionInf__fuseAsyn_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArgs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::Ice::Int __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::begin_fuseAsyn(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCWiseFuse__WiseFusionInf__fuseAsyn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCWiseFuse__WiseFusionInf__fuseAsyn_name, __del, __cookie);
    try
    {
        __result->prepare(__RPCWiseFuse__WiseFusionInf__fuseAsyn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArgs);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::__begin_fuseAsyn(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RPCWiseFuse::WiseFusionInfPrx __proxy = ::RPCWiseFuse::WiseFusionInfPrx::uncheckedCast(__result->getProxy());
            ::Ice::Int __ret;
            try
            {
                __ret = __proxy->end_fuseAsyn(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (::Ice::Int)> _response;
    };
    return begin_fuseAsyn(__p_mapArgs, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::Ice::Int
IceProxy::RPCWiseFuse::WiseFusionInf::end_fuseAsyn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCWiseFuse__WiseFusionInf__fuseAsyn_name);
    ::Ice::Int __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

::std::string
IceProxy::RPCWiseFuse::WiseFusionInf::askProcess(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RPCWiseFuse__WiseFusionInf__askProcess_name);
    ::IceInternal::Outgoing __og(this, __RPCWiseFuse__WiseFusionInf__askProcess_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArgs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::std::string __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::begin_askProcess(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCWiseFuse__WiseFusionInf__askProcess_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCWiseFuse__WiseFusionInf__askProcess_name, __del, __cookie);
    try
    {
        __result->prepare(__RPCWiseFuse__WiseFusionInf__askProcess_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArgs);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::__begin_askProcess(const ::RPCWiseFuse::DirArgs& __p_mapArgs, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RPCWiseFuse::WiseFusionInfPrx __proxy = ::RPCWiseFuse::WiseFusionInfPrx::uncheckedCast(__result->getProxy());
            ::std::string __ret;
            try
            {
                __ret = __proxy->end_askProcess(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::std::string&)> _response;
    };
    return begin_askProcess(__p_mapArgs, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::std::string
IceProxy::RPCWiseFuse::WiseFusionInf::end_askProcess(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCWiseFuse__WiseFusionInf__askProcess_name);
    ::std::string __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

::RPCWiseFuse::FusionInf
IceProxy::RPCWiseFuse::WiseFusionInf::fetchFuseRes(const ::RPCWiseFuse::DirArgs& __p_mapArg, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RPCWiseFuse__WiseFusionInf__fetchFuseRes_name);
    ::IceInternal::Outgoing __og(this, __RPCWiseFuse__WiseFusionInf__fetchFuseRes_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArg);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::RPCWiseFuse::FusionInf __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::begin_fetchFuseRes(const ::RPCWiseFuse::DirArgs& __p_mapArg, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCWiseFuse__WiseFusionInf__fetchFuseRes_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCWiseFuse__WiseFusionInf__fetchFuseRes_name, __del, __cookie);
    try
    {
        __result->prepare(__RPCWiseFuse__WiseFusionInf__fetchFuseRes_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_mapArg);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RPCWiseFuse::WiseFusionInf::__begin_fetchFuseRes(const ::RPCWiseFuse::DirArgs& __p_mapArg, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RPCWiseFuse::FusionInf&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RPCWiseFuse::FusionInf&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RPCWiseFuse::WiseFusionInfPrx __proxy = ::RPCWiseFuse::WiseFusionInfPrx::uncheckedCast(__result->getProxy());
            ::RPCWiseFuse::FusionInf __ret;
            try
            {
                __ret = __proxy->end_fetchFuseRes(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::RPCWiseFuse::FusionInf&)> _response;
    };
    return begin_fetchFuseRes(__p_mapArg, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::RPCWiseFuse::FusionInf
IceProxy::RPCWiseFuse::WiseFusionInf::end_fetchFuseRes(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCWiseFuse__WiseFusionInf__fetchFuseRes_name);
    ::RPCWiseFuse::FusionInf __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::RPCWiseFuse::WiseFusionInf::ice_staticId()
{
    return ::RPCWiseFuse::WiseFusionInf::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RPCWiseFuse::WiseFusionInf::__newInstance() const
{
    return new WiseFusionInf;
}

::Ice::Object* RPCWiseFuse::upCast(::RPCWiseFuse::WiseFusionInf* p) { return p; }

namespace
{
const ::std::string __RPCWiseFuse__WiseFusionInf_ids[2] =
{
    "::Ice::Object",
    "::RPCWiseFuse::WiseFusionInf"
};

}

bool
RPCWiseFuse::WiseFusionInf::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RPCWiseFuse__WiseFusionInf_ids, __RPCWiseFuse__WiseFusionInf_ids + 2, _s);
}

::std::vector< ::std::string>
RPCWiseFuse::WiseFusionInf::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RPCWiseFuse__WiseFusionInf_ids[0], &__RPCWiseFuse__WiseFusionInf_ids[2]);
}

const ::std::string&
RPCWiseFuse::WiseFusionInf::ice_id(const ::Ice::Current&) const
{
    return __RPCWiseFuse__WiseFusionInf_ids[1];
}

const ::std::string&
RPCWiseFuse::WiseFusionInf::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RPCWiseFuse::WiseFusionInf";
    return typeId;
#else
    return __RPCWiseFuse__WiseFusionInf_ids[1];
#endif
}

::Ice::DispatchStatus
RPCWiseFuse::WiseFusionInf::___geneThumbImg(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string __p_inPath;
    ::std::string __p_outPath;
    ::std::string __p_bandlist;
    __is->read(__p_inPath);
    __is->read(__p_outPath);
    __is->read(__p_bandlist);
    __inS.endReadParams();
    bool __ret = geneThumbImg(__p_inPath, __p_outPath, __p_bandlist, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RPCWiseFuse::WiseFusionInf::___fuseSyn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RPCWiseFuse::DirArgs __p_mapArgs;
    __is->read(__p_mapArgs);
    __inS.endReadParams();
    ::RPCWiseFuse::FusionInf __ret = fuseSyn(__p_mapArgs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RPCWiseFuse::WiseFusionInf::___fuseAsyn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RPCWiseFuse::DirArgs __p_mapArgs;
    __is->read(__p_mapArgs);
    __inS.endReadParams();
    ::Ice::Int __ret = fuseAsyn(__p_mapArgs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RPCWiseFuse::WiseFusionInf::___askProcess(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RPCWiseFuse::DirArgs __p_mapArgs;
    __is->read(__p_mapArgs);
    __inS.endReadParams();
    ::std::string __ret = askProcess(__p_mapArgs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RPCWiseFuse::WiseFusionInf::___fetchFuseRes(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RPCWiseFuse::DirArgs __p_mapArg;
    __is->read(__p_mapArg);
    __inS.endReadParams();
    ::RPCWiseFuse::FusionInf __ret = fetchFuseRes(__p_mapArg, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RPCWiseFuse__WiseFusionInf_all[] =
{
    "askProcess",
    "fetchFuseRes",
    "fuseAsyn",
    "fuseSyn",
    "geneThumbImg",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RPCWiseFuse::WiseFusionInf::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RPCWiseFuse__WiseFusionInf_all, __RPCWiseFuse__WiseFusionInf_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RPCWiseFuse__WiseFusionInf_all)
    {
        case 0:
        {
            return ___askProcess(in, current);
        }
        case 1:
        {
            return ___fetchFuseRes(in, current);
        }
        case 2:
        {
            return ___fuseAsyn(in, current);
        }
        case 3:
        {
            return ___fuseSyn(in, current);
        }
        case 4:
        {
            return ___geneThumbImg(in, current);
        }
        case 5:
        {
            return ___ice_id(in, current);
        }
        case 6:
        {
            return ___ice_ids(in, current);
        }
        case 7:
        {
            return ___ice_isA(in, current);
        }
        case 8:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RPCWiseFuse::WiseFusionInf::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RPCWiseFuse::WiseFusionInf::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RPCWiseFuse::__patch(WiseFusionInfPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RPCWiseFuse::WiseFusionInfPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RPCWiseFuse::WiseFusionInf::ice_staticId(), v);
    }
}
