#############################################################################
# Makefile for building: ImageFusion
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ImageFusion.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile ImageFusion.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -std=c++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Imain/src/algorithm/fusion/gdal/include -Imain/src/algorithm/fusion/proj/include -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ImageFusion1.0.0
DISTDIR = /home/fighter/Documents/ImageFusion/.tmp/ImageFusion1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -lIce -lIceUtil -lpthread -L/usr/local/lib -lproj -lgdal 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main/Server.cpp \
		main/src/utils/readconf.cpp \
		main/src/utils/log.cpp \
		main/src/rpc/wisefuseRpc.cpp \
		main/src/threadpool/ThreadPool.cpp \
		main/src/threadpool/Task.cpp \
		main/src/threadpool/Mutex.cpp \
		main/src/algorithm/fusion/Tools.cpp \
		main/src/algorithm/fusion/PCAFusion.cpp \
		main/src/algorithm/fusion/PCA.cpp \
		main/src/algorithm/fusion/HSIFusion.cpp \
		main/src/algorithm/fusion/HSI.cpp \
		main/src/algorithm/fusion/HCSFusion.cpp \
		main/src/algorithm/fusion/HCS.cpp \
		main/src/algorithm/fusion/GramSchmidtFusion.cpp \
		main/src/algorithm/fusion/DWTFusion.cpp \
		main/src/algorithm/fusion/CurveletFusion.cpp \
		main/src/algorithm/fusion/BroveyFusion.cpp \
		main/src/algorithm/fusion/curvelet/ifdct_wrapping.cpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping.cpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_param.cpp \
		main/src/algorithm/fusion/curvelet/fftw/wisdomio.c \
		main/src/algorithm/fusion/curvelet/fftw/wisdom.c \
		main/src/algorithm/fusion/curvelet/fftw/twiddle.c \
		main/src/algorithm/fusion/curvelet/fftw/timer.c \
		main/src/algorithm/fusion/curvelet/fftw/rader.c \
		main/src/algorithm/fusion/curvelet/fftw/putils.c \
		main/src/algorithm/fusion/curvelet/fftw/planner.c \
		main/src/algorithm/fusion/curvelet/fftw/generic.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_64.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_32.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_16.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_10.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_9.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_8.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_7.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_6.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_5.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_4.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_3.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_2.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_64.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_32.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_16.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_10.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_9.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_8.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_7.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_6.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_5.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_4.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_3.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_2.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_64.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_32.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_16.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_15.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_14.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_13.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_12.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_11.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_10.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_9.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_8.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_7.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_6.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_5.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_4.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_3.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_2.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_1.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_64.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_32.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_16.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_15.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_14.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_13.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_12.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_11.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_10.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_9.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_8.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_7.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_6.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_5.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_4.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_3.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_2.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_1.c \
		main/src/algorithm/fusion/curvelet/fftw/fftwnd.c \
		main/src/algorithm/fusion/curvelet/fftw/fftwf77.c \
		main/src/algorithm/fusion/curvelet/fftw/executor.c \
		main/src/algorithm/fusion/curvelet/fftw/config.c \
		main/src/algorithm/fusion/curvelet/fftw/malloc.cpp \
		main/src/utils/utils.cpp \
		main/src/algorithm/fusion/Fusion.cpp \
		main/src/algorithm/fusion/PgInf.cpp \
		main/src/algorithm/fusion/GdalInf.cpp 
OBJECTS       = Server.o \
		readconf.o \
		log.o \
		wisefuseRpc.o \
		ThreadPool.o \
		Task.o \
		Mutex.o \
		Tools.o \
		PCAFusion.o \
		PCA.o \
		HSIFusion.o \
		HSI.o \
		HCSFusion.o \
		HCS.o \
		GramSchmidtFusion.o \
		DWTFusion.o \
		CurveletFusion.o \
		BroveyFusion.o \
		ifdct_wrapping.o \
		fdct_wrapping.o \
		fdct_wrapping_param.o \
		wisdomio.o \
		wisdom.o \
		twiddle.o \
		timer.o \
		rader.o \
		putils.o \
		planner.o \
		generic.o \
		ftwi_64.o \
		ftwi_32.o \
		ftwi_16.o \
		ftwi_10.o \
		ftwi_9.o \
		ftwi_8.o \
		ftwi_7.o \
		ftwi_6.o \
		ftwi_5.o \
		ftwi_4.o \
		ftwi_3.o \
		ftwi_2.o \
		ftw_64.o \
		ftw_32.o \
		ftw_16.o \
		ftw_10.o \
		ftw_9.o \
		ftw_8.o \
		ftw_7.o \
		ftw_6.o \
		ftw_5.o \
		ftw_4.o \
		ftw_3.o \
		ftw_2.o \
		fni_64.o \
		fni_32.o \
		fni_16.o \
		fni_15.o \
		fni_14.o \
		fni_13.o \
		fni_12.o \
		fni_11.o \
		fni_10.o \
		fni_9.o \
		fni_8.o \
		fni_7.o \
		fni_6.o \
		fni_5.o \
		fni_4.o \
		fni_3.o \
		fni_2.o \
		fni_1.o \
		fn_64.o \
		fn_32.o \
		fn_16.o \
		fn_15.o \
		fn_14.o \
		fn_13.o \
		fn_12.o \
		fn_11.o \
		fn_10.o \
		fn_9.o \
		fn_8.o \
		fn_7.o \
		fn_6.o \
		fn_5.o \
		fn_4.o \
		fn_3.o \
		fn_2.o \
		fn_1.o \
		fftwnd.o \
		fftwf77.o \
		executor.o \
		config.o \
		malloc.o \
		utils.o \
		Fusion.o \
		PgInf.o \
		GdalInf.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ImageFusion.pro main/Server.h \
		main/src/utils/log.h \
		main/src/rpc/wisefuseRpc.h \
		main/src/threadpool/ThreadPool.h \
		main/src/threadpool/Task.h \
		main/src/threadpool/Mutex.h \
		main/src/algorithm/fusion/WT.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/PgInf.h \
		main/src/algorithm/fusion/PCAFusion.h \
		main/src/algorithm/fusion/PCA.h \
		main/src/algorithm/fusion/HSIFusion.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/HCSFusion.h \
		main/src/algorithm/fusion/HCS.h \
		main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/DWTFusion.h \
		main/src/algorithm/fusion/CurveletFusion.h \
		main/src/algorithm/fusion/BroveyFusion.h \
		main/src/algorithm/fusion/curvelet/offvec.hpp \
		main/src/algorithm/fusion/curvelet/offmat.hpp \
		main/src/algorithm/fusion/curvelet/numvec.hpp \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inline.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/Fusion.h \
		main/src/utils/utils.h main/Server.cpp \
		main/src/utils/readconf.cpp \
		main/src/utils/log.cpp \
		main/src/rpc/wisefuseRpc.cpp \
		main/src/threadpool/ThreadPool.cpp \
		main/src/threadpool/Task.cpp \
		main/src/threadpool/Mutex.cpp \
		main/src/algorithm/fusion/Tools.cpp \
		main/src/algorithm/fusion/PCAFusion.cpp \
		main/src/algorithm/fusion/PCA.cpp \
		main/src/algorithm/fusion/HSIFusion.cpp \
		main/src/algorithm/fusion/HSI.cpp \
		main/src/algorithm/fusion/HCSFusion.cpp \
		main/src/algorithm/fusion/HCS.cpp \
		main/src/algorithm/fusion/GramSchmidtFusion.cpp \
		main/src/algorithm/fusion/DWTFusion.cpp \
		main/src/algorithm/fusion/CurveletFusion.cpp \
		main/src/algorithm/fusion/BroveyFusion.cpp \
		main/src/algorithm/fusion/curvelet/ifdct_wrapping.cpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping.cpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_param.cpp \
		main/src/algorithm/fusion/curvelet/fftw/wisdomio.c \
		main/src/algorithm/fusion/curvelet/fftw/wisdom.c \
		main/src/algorithm/fusion/curvelet/fftw/twiddle.c \
		main/src/algorithm/fusion/curvelet/fftw/timer.c \
		main/src/algorithm/fusion/curvelet/fftw/rader.c \
		main/src/algorithm/fusion/curvelet/fftw/putils.c \
		main/src/algorithm/fusion/curvelet/fftw/planner.c \
		main/src/algorithm/fusion/curvelet/fftw/generic.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_64.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_32.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_16.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_10.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_9.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_8.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_7.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_6.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_5.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_4.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_3.c \
		main/src/algorithm/fusion/curvelet/fftw/ftwi_2.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_64.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_32.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_16.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_10.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_9.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_8.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_7.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_6.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_5.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_4.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_3.c \
		main/src/algorithm/fusion/curvelet/fftw/ftw_2.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_64.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_32.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_16.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_15.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_14.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_13.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_12.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_11.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_10.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_9.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_8.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_7.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_6.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_5.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_4.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_3.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_2.c \
		main/src/algorithm/fusion/curvelet/fftw/fni_1.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_64.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_32.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_16.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_15.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_14.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_13.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_12.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_11.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_10.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_9.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_8.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_7.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_6.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_5.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_4.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_3.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_2.c \
		main/src/algorithm/fusion/curvelet/fftw/fn_1.c \
		main/src/algorithm/fusion/curvelet/fftw/fftwnd.c \
		main/src/algorithm/fusion/curvelet/fftw/fftwf77.c \
		main/src/algorithm/fusion/curvelet/fftw/executor.c \
		main/src/algorithm/fusion/curvelet/fftw/config.c \
		main/src/algorithm/fusion/curvelet/fftw/malloc.cpp \
		main/src/utils/utils.cpp \
		main/src/algorithm/fusion/Fusion.cpp \
		main/src/algorithm/fusion/PgInf.cpp \
		main/src/algorithm/fusion/GdalInf.cpp
QMAKE_TARGET  = ImageFusion
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ImageFusion


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ImageFusion.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ImageFusion.pro
	$(QMAKE) -o Makefile ImageFusion.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ImageFusion.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ImageFusion.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Server.o: main/Server.cpp main/Server.h \
		main/src/rpc/wisefuseRpc.h \
		main/src/utils/log.h \
		main/src/utils/utils.h \
		main/src/algorithm/fusion/Fusion.h \
		main/src/algorithm/fusion/BroveyFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSIFusion.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/HCSFusion.h \
		main/src/algorithm/fusion/HCS.h \
		main/src/algorithm/fusion/PCAFusion.h \
		main/src/algorithm/fusion/PCA.h \
		main/src/algorithm/fusion/DWTFusion.h \
		main/src/algorithm/fusion/CurveletFusion.h \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/algorithm/fusion/PgInf.h \
		main/src/algorithm/fusion/proj/include/proj_api.h \
		main/src/threadpool/ThreadPool.h \
		main/src/threadpool/Mutex.h \
		main/src/threadpool/Task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Server.o main/Server.cpp

readconf.o: main/src/utils/readconf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readconf.o main/src/utils/readconf.cpp

log.o: main/src/utils/log.cpp main/src/utils/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log.o main/src/utils/log.cpp

wisefuseRpc.o: main/src/rpc/wisefuseRpc.cpp main/src/rpc/wisefuseRpc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wisefuseRpc.o main/src/rpc/wisefuseRpc.cpp

ThreadPool.o: main/src/threadpool/ThreadPool.cpp main/src/threadpool/ThreadPool.h \
		main/src/threadpool/Mutex.h \
		main/src/threadpool/Task.h \
		main/src/algorithm/fusion/PgInf.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/proj/include/proj_api.h \
		main/src/utils/utils.h \
		main/src/algorithm/fusion/Fusion.h \
		main/src/algorithm/fusion/BroveyFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSIFusion.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/HCSFusion.h \
		main/src/algorithm/fusion/HCS.h \
		main/src/algorithm/fusion/PCAFusion.h \
		main/src/algorithm/fusion/PCA.h \
		main/src/algorithm/fusion/DWTFusion.h \
		main/src/algorithm/fusion/CurveletFusion.h \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/rpc/wisefuseRpc.h \
		main/src/utils/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThreadPool.o main/src/threadpool/ThreadPool.cpp

Task.o: main/src/threadpool/Task.cpp main/src/threadpool/Task.h \
		main/src/algorithm/fusion/PgInf.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/proj/include/proj_api.h \
		main/src/utils/utils.h \
		main/src/algorithm/fusion/Fusion.h \
		main/src/algorithm/fusion/BroveyFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSIFusion.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/HCSFusion.h \
		main/src/algorithm/fusion/HCS.h \
		main/src/algorithm/fusion/PCAFusion.h \
		main/src/algorithm/fusion/PCA.h \
		main/src/algorithm/fusion/DWTFusion.h \
		main/src/algorithm/fusion/CurveletFusion.h \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/rpc/wisefuseRpc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Task.o main/src/threadpool/Task.cpp

Mutex.o: main/src/threadpool/Mutex.cpp main/src/threadpool/Mutex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mutex.o main/src/threadpool/Mutex.cpp

Tools.o: main/src/algorithm/fusion/Tools.cpp main/src/algorithm/fusion/Tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tools.o main/src/algorithm/fusion/Tools.cpp

PCAFusion.o: main/src/algorithm/fusion/PCAFusion.cpp main/src/algorithm/fusion/PCAFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/PCA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PCAFusion.o main/src/algorithm/fusion/PCAFusion.cpp

PCA.o: main/src/algorithm/fusion/PCA.cpp main/src/algorithm/fusion/PCA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PCA.o main/src/algorithm/fusion/PCA.cpp

HSIFusion.o: main/src/algorithm/fusion/HSIFusion.cpp main/src/algorithm/fusion/HSIFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HSIFusion.o main/src/algorithm/fusion/HSIFusion.cpp

HSI.o: main/src/algorithm/fusion/HSI.cpp main/src/algorithm/fusion/HSI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HSI.o main/src/algorithm/fusion/HSI.cpp

HCSFusion.o: main/src/algorithm/fusion/HCSFusion.cpp main/src/algorithm/fusion/HCSFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HCS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HCSFusion.o main/src/algorithm/fusion/HCSFusion.cpp

HCS.o: main/src/algorithm/fusion/HCS.cpp main/src/algorithm/fusion/HCS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HCS.o main/src/algorithm/fusion/HCS.cpp

GramSchmidtFusion.o: main/src/algorithm/fusion/GramSchmidtFusion.cpp main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GramSchmidtFusion.o main/src/algorithm/fusion/GramSchmidtFusion.cpp

DWTFusion.o: main/src/algorithm/fusion/DWTFusion.cpp main/src/algorithm/fusion/DWTFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/WT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DWTFusion.o main/src/algorithm/fusion/DWTFusion.cpp

CurveletFusion.o: main/src/algorithm/fusion/CurveletFusion.cpp main/src/algorithm/fusion/CurveletFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/HCS.h \
		main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/algorithm/fusion/curvelet/fdct_wrapping.hpp \
		main/src/algorithm/fusion/curvelet/numvec.hpp \
		main/src/algorithm/fusion/curvelet/offvec.hpp \
		main/src/algorithm/fusion/curvelet/offmat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inline.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CurveletFusion.o main/src/algorithm/fusion/CurveletFusion.cpp

BroveyFusion.o: main/src/algorithm/fusion/BroveyFusion.cpp main/src/algorithm/fusion/BroveyFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BroveyFusion.o main/src/algorithm/fusion/BroveyFusion.cpp

ifdct_wrapping.o: main/src/algorithm/fusion/curvelet/ifdct_wrapping.cpp main/src/algorithm/fusion/curvelet/fdct_wrapping.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/curvelet/numvec.hpp \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/offvec.hpp \
		main/src/algorithm/fusion/curvelet/offmat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inline.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ifdct_wrapping.o main/src/algorithm/fusion/curvelet/ifdct_wrapping.cpp

fdct_wrapping.o: main/src/algorithm/fusion/curvelet/fdct_wrapping.cpp main/src/algorithm/fusion/curvelet/fdct_wrapping.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/curvelet/numvec.hpp \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/offvec.hpp \
		main/src/algorithm/fusion/curvelet/offmat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inline.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fdct_wrapping.o main/src/algorithm/fusion/curvelet/fdct_wrapping.cpp

fdct_wrapping_param.o: main/src/algorithm/fusion/curvelet/fdct_wrapping_param.cpp main/src/algorithm/fusion/curvelet/fdct_wrapping.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/curvelet/numvec.hpp \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/offvec.hpp \
		main/src/algorithm/fusion/curvelet/offmat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inline.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fdct_wrapping_param.o main/src/algorithm/fusion/curvelet/fdct_wrapping_param.cpp

wisdomio.o: main/src/algorithm/fusion/curvelet/fftw/wisdomio.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wisdomio.o main/src/algorithm/fusion/curvelet/fftw/wisdomio.c

wisdom.o: main/src/algorithm/fusion/curvelet/fftw/wisdom.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wisdom.o main/src/algorithm/fusion/curvelet/fftw/wisdom.c

twiddle.o: main/src/algorithm/fusion/curvelet/fftw/twiddle.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o twiddle.o main/src/algorithm/fusion/curvelet/fftw/twiddle.c

timer.o: main/src/algorithm/fusion/curvelet/fftw/timer.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o timer.o main/src/algorithm/fusion/curvelet/fftw/timer.c

rader.o: main/src/algorithm/fusion/curvelet/fftw/rader.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rader.o main/src/algorithm/fusion/curvelet/fftw/rader.c

putils.o: main/src/algorithm/fusion/curvelet/fftw/putils.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o putils.o main/src/algorithm/fusion/curvelet/fftw/putils.c

planner.o: main/src/algorithm/fusion/curvelet/fftw/planner.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o planner.o main/src/algorithm/fusion/curvelet/fftw/planner.c

generic.o: main/src/algorithm/fusion/curvelet/fftw/generic.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o generic.o main/src/algorithm/fusion/curvelet/fftw/generic.c

ftwi_64.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_64.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_64.o main/src/algorithm/fusion/curvelet/fftw/ftwi_64.c

ftwi_32.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_32.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_32.o main/src/algorithm/fusion/curvelet/fftw/ftwi_32.c

ftwi_16.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_16.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_16.o main/src/algorithm/fusion/curvelet/fftw/ftwi_16.c

ftwi_10.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_10.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_10.o main/src/algorithm/fusion/curvelet/fftw/ftwi_10.c

ftwi_9.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_9.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_9.o main/src/algorithm/fusion/curvelet/fftw/ftwi_9.c

ftwi_8.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_8.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_8.o main/src/algorithm/fusion/curvelet/fftw/ftwi_8.c

ftwi_7.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_7.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_7.o main/src/algorithm/fusion/curvelet/fftw/ftwi_7.c

ftwi_6.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_6.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_6.o main/src/algorithm/fusion/curvelet/fftw/ftwi_6.c

ftwi_5.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_5.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_5.o main/src/algorithm/fusion/curvelet/fftw/ftwi_5.c

ftwi_4.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_4.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_4.o main/src/algorithm/fusion/curvelet/fftw/ftwi_4.c

ftwi_3.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_3.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_3.o main/src/algorithm/fusion/curvelet/fftw/ftwi_3.c

ftwi_2.o: main/src/algorithm/fusion/curvelet/fftw/ftwi_2.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftwi_2.o main/src/algorithm/fusion/curvelet/fftw/ftwi_2.c

ftw_64.o: main/src/algorithm/fusion/curvelet/fftw/ftw_64.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_64.o main/src/algorithm/fusion/curvelet/fftw/ftw_64.c

ftw_32.o: main/src/algorithm/fusion/curvelet/fftw/ftw_32.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_32.o main/src/algorithm/fusion/curvelet/fftw/ftw_32.c

ftw_16.o: main/src/algorithm/fusion/curvelet/fftw/ftw_16.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_16.o main/src/algorithm/fusion/curvelet/fftw/ftw_16.c

ftw_10.o: main/src/algorithm/fusion/curvelet/fftw/ftw_10.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_10.o main/src/algorithm/fusion/curvelet/fftw/ftw_10.c

ftw_9.o: main/src/algorithm/fusion/curvelet/fftw/ftw_9.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_9.o main/src/algorithm/fusion/curvelet/fftw/ftw_9.c

ftw_8.o: main/src/algorithm/fusion/curvelet/fftw/ftw_8.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_8.o main/src/algorithm/fusion/curvelet/fftw/ftw_8.c

ftw_7.o: main/src/algorithm/fusion/curvelet/fftw/ftw_7.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_7.o main/src/algorithm/fusion/curvelet/fftw/ftw_7.c

ftw_6.o: main/src/algorithm/fusion/curvelet/fftw/ftw_6.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_6.o main/src/algorithm/fusion/curvelet/fftw/ftw_6.c

ftw_5.o: main/src/algorithm/fusion/curvelet/fftw/ftw_5.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_5.o main/src/algorithm/fusion/curvelet/fftw/ftw_5.c

ftw_4.o: main/src/algorithm/fusion/curvelet/fftw/ftw_4.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_4.o main/src/algorithm/fusion/curvelet/fftw/ftw_4.c

ftw_3.o: main/src/algorithm/fusion/curvelet/fftw/ftw_3.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_3.o main/src/algorithm/fusion/curvelet/fftw/ftw_3.c

ftw_2.o: main/src/algorithm/fusion/curvelet/fftw/ftw_2.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftw_2.o main/src/algorithm/fusion/curvelet/fftw/ftw_2.c

fni_64.o: main/src/algorithm/fusion/curvelet/fftw/fni_64.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_64.o main/src/algorithm/fusion/curvelet/fftw/fni_64.c

fni_32.o: main/src/algorithm/fusion/curvelet/fftw/fni_32.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_32.o main/src/algorithm/fusion/curvelet/fftw/fni_32.c

fni_16.o: main/src/algorithm/fusion/curvelet/fftw/fni_16.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_16.o main/src/algorithm/fusion/curvelet/fftw/fni_16.c

fni_15.o: main/src/algorithm/fusion/curvelet/fftw/fni_15.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_15.o main/src/algorithm/fusion/curvelet/fftw/fni_15.c

fni_14.o: main/src/algorithm/fusion/curvelet/fftw/fni_14.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_14.o main/src/algorithm/fusion/curvelet/fftw/fni_14.c

fni_13.o: main/src/algorithm/fusion/curvelet/fftw/fni_13.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_13.o main/src/algorithm/fusion/curvelet/fftw/fni_13.c

fni_12.o: main/src/algorithm/fusion/curvelet/fftw/fni_12.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_12.o main/src/algorithm/fusion/curvelet/fftw/fni_12.c

fni_11.o: main/src/algorithm/fusion/curvelet/fftw/fni_11.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_11.o main/src/algorithm/fusion/curvelet/fftw/fni_11.c

fni_10.o: main/src/algorithm/fusion/curvelet/fftw/fni_10.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_10.o main/src/algorithm/fusion/curvelet/fftw/fni_10.c

fni_9.o: main/src/algorithm/fusion/curvelet/fftw/fni_9.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_9.o main/src/algorithm/fusion/curvelet/fftw/fni_9.c

fni_8.o: main/src/algorithm/fusion/curvelet/fftw/fni_8.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_8.o main/src/algorithm/fusion/curvelet/fftw/fni_8.c

fni_7.o: main/src/algorithm/fusion/curvelet/fftw/fni_7.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_7.o main/src/algorithm/fusion/curvelet/fftw/fni_7.c

fni_6.o: main/src/algorithm/fusion/curvelet/fftw/fni_6.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_6.o main/src/algorithm/fusion/curvelet/fftw/fni_6.c

fni_5.o: main/src/algorithm/fusion/curvelet/fftw/fni_5.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_5.o main/src/algorithm/fusion/curvelet/fftw/fni_5.c

fni_4.o: main/src/algorithm/fusion/curvelet/fftw/fni_4.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_4.o main/src/algorithm/fusion/curvelet/fftw/fni_4.c

fni_3.o: main/src/algorithm/fusion/curvelet/fftw/fni_3.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_3.o main/src/algorithm/fusion/curvelet/fftw/fni_3.c

fni_2.o: main/src/algorithm/fusion/curvelet/fftw/fni_2.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_2.o main/src/algorithm/fusion/curvelet/fftw/fni_2.c

fni_1.o: main/src/algorithm/fusion/curvelet/fftw/fni_1.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fni_1.o main/src/algorithm/fusion/curvelet/fftw/fni_1.c

fn_64.o: main/src/algorithm/fusion/curvelet/fftw/fn_64.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_64.o main/src/algorithm/fusion/curvelet/fftw/fn_64.c

fn_32.o: main/src/algorithm/fusion/curvelet/fftw/fn_32.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_32.o main/src/algorithm/fusion/curvelet/fftw/fn_32.c

fn_16.o: main/src/algorithm/fusion/curvelet/fftw/fn_16.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_16.o main/src/algorithm/fusion/curvelet/fftw/fn_16.c

fn_15.o: main/src/algorithm/fusion/curvelet/fftw/fn_15.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_15.o main/src/algorithm/fusion/curvelet/fftw/fn_15.c

fn_14.o: main/src/algorithm/fusion/curvelet/fftw/fn_14.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_14.o main/src/algorithm/fusion/curvelet/fftw/fn_14.c

fn_13.o: main/src/algorithm/fusion/curvelet/fftw/fn_13.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_13.o main/src/algorithm/fusion/curvelet/fftw/fn_13.c

fn_12.o: main/src/algorithm/fusion/curvelet/fftw/fn_12.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_12.o main/src/algorithm/fusion/curvelet/fftw/fn_12.c

fn_11.o: main/src/algorithm/fusion/curvelet/fftw/fn_11.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_11.o main/src/algorithm/fusion/curvelet/fftw/fn_11.c

fn_10.o: main/src/algorithm/fusion/curvelet/fftw/fn_10.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_10.o main/src/algorithm/fusion/curvelet/fftw/fn_10.c

fn_9.o: main/src/algorithm/fusion/curvelet/fftw/fn_9.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_9.o main/src/algorithm/fusion/curvelet/fftw/fn_9.c

fn_8.o: main/src/algorithm/fusion/curvelet/fftw/fn_8.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_8.o main/src/algorithm/fusion/curvelet/fftw/fn_8.c

fn_7.o: main/src/algorithm/fusion/curvelet/fftw/fn_7.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_7.o main/src/algorithm/fusion/curvelet/fftw/fn_7.c

fn_6.o: main/src/algorithm/fusion/curvelet/fftw/fn_6.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_6.o main/src/algorithm/fusion/curvelet/fftw/fn_6.c

fn_5.o: main/src/algorithm/fusion/curvelet/fftw/fn_5.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_5.o main/src/algorithm/fusion/curvelet/fftw/fn_5.c

fn_4.o: main/src/algorithm/fusion/curvelet/fftw/fn_4.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_4.o main/src/algorithm/fusion/curvelet/fftw/fn_4.c

fn_3.o: main/src/algorithm/fusion/curvelet/fftw/fn_3.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_3.o main/src/algorithm/fusion/curvelet/fftw/fn_3.c

fn_2.o: main/src/algorithm/fusion/curvelet/fftw/fn_2.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_2.o main/src/algorithm/fusion/curvelet/fftw/fn_2.c

fn_1.o: main/src/algorithm/fusion/curvelet/fftw/fn_1.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fn_1.o main/src/algorithm/fusion/curvelet/fftw/fn_1.c

fftwnd.o: main/src/algorithm/fusion/curvelet/fftw/fftwnd.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fftwnd.o main/src/algorithm/fusion/curvelet/fftw/fftwnd.c

fftwf77.o: main/src/algorithm/fusion/curvelet/fftw/fftwf77.c main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fftwf77.o main/src/algorithm/fusion/curvelet/fftw/fftwf77.c

executor.o: main/src/algorithm/fusion/curvelet/fftw/executor.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o executor.o main/src/algorithm/fusion/curvelet/fftw/executor.c

config.o: main/src/algorithm/fusion/curvelet/fftw/config.c main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o config.o main/src/algorithm/fusion/curvelet/fftw/config.c

malloc.o: main/src/algorithm/fusion/curvelet/fftw/malloc.cpp main/src/algorithm/fusion/curvelet/fftw/fftw-int.h \
		main/src/algorithm/fusion/curvelet/fftw/config.h \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o malloc.o main/src/algorithm/fusion/curvelet/fftw/malloc.cpp

utils.o: main/src/utils/utils.cpp main/src/utils/utils.h \
		main/src/algorithm/fusion/Fusion.h \
		main/src/algorithm/fusion/BroveyFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSIFusion.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/HCSFusion.h \
		main/src/algorithm/fusion/HCS.h \
		main/src/algorithm/fusion/PCAFusion.h \
		main/src/algorithm/fusion/PCA.h \
		main/src/algorithm/fusion/DWTFusion.h \
		main/src/algorithm/fusion/CurveletFusion.h \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/algorithm/fusion/PgInf.h \
		main/src/algorithm/fusion/proj/include/proj_api.h \
		main/src/rpc/wisefuseRpc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o main/src/utils/utils.cpp

Fusion.o: main/src/algorithm/fusion/Fusion.cpp main/src/algorithm/fusion/Fusion.h \
		main/src/algorithm/fusion/BroveyFusion.h \
		main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h \
		main/src/algorithm/fusion/Tools.h \
		main/src/algorithm/fusion/HSIFusion.h \
		main/src/algorithm/fusion/HSI.h \
		main/src/algorithm/fusion/HCSFusion.h \
		main/src/algorithm/fusion/HCS.h \
		main/src/algorithm/fusion/PCAFusion.h \
		main/src/algorithm/fusion/PCA.h \
		main/src/algorithm/fusion/DWTFusion.h \
		main/src/algorithm/fusion/CurveletFusion.h \
		main/src/algorithm/fusion/curvelet/nummat.hpp \
		main/src/algorithm/fusion/curvelet/fdct_wrapping_inc.hpp \
		main/src/algorithm/fusion/curvelet/fftw/fftw.h \
		main/src/algorithm/fusion/GramSchmidtFusion.h \
		main/src/algorithm/fusion/PgInf.h \
		main/src/algorithm/fusion/proj/include/proj_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fusion.o main/src/algorithm/fusion/Fusion.cpp

PgInf.o: main/src/algorithm/fusion/PgInf.cpp main/src/algorithm/fusion/PgInf.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/proj/include/proj_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PgInf.o main/src/algorithm/fusion/PgInf.cpp

GdalInf.o: main/src/algorithm/fusion/GdalInf.cpp main/src/algorithm/fusion/GdalInf.h \
		main/src/algorithm/fusion/gdal/include/gdal.h \
		main/src/algorithm/fusion/gdal/include/gdal_version.h \
		main/src/algorithm/fusion/gdal/include/cpl_port.h \
		main/src/algorithm/fusion/gdal/include/cpl_config.h \
		main/src/algorithm/fusion/gdal/include/cpl_error.h \
		main/src/algorithm/fusion/gdal/include/cpl_progress.h \
		main/src/algorithm/fusion/gdal/include/cpl_virtualmem.h \
		main/src/algorithm/fusion/gdal/include/cpl_vsi.h \
		main/src/algorithm/fusion/gdal/include/cpl_minixml.h \
		main/src/algorithm/fusion/gdal/include/ogr_api.h \
		main/src/algorithm/fusion/gdal/include/ogr_core.h \
		main/src/algorithm/fusion/gdal/include/gdal_priv.h \
		main/src/algorithm/fusion/gdal/include/gdal_frmts.h \
		main/src/algorithm/fusion/gdal/include/cpl_conv.h \
		main/src/algorithm/fusion/gdal/include/cpl_string.h \
		main/src/algorithm/fusion/gdal/include/cpl_multiproc.h \
		main/src/algorithm/fusion/gdal/include/ogr_spatialref.h \
		main/src/algorithm/fusion/gdal/include/ogr_srs_api.h \
		main/src/algorithm/fusion/gdal/include/gdalwarper.h \
		main/src/algorithm/fusion/gdal/include/gdal_alg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GdalInf.o main/src/algorithm/fusion/GdalInf.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

