// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `qualityjudgeRpc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "qualityjudgeRpc.h"
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RPCQualityJudge__QualityInf__qualitySyn_name = "qualitySyn";

const ::std::string __RPCQualityJudge__QualityInf__qualityAsyn_name = "qualityAsyn";

const ::std::string __RPCQualityJudge__QualityInf__fetchQualityRes_name = "fetchQualityRes";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RPCQualityJudge::upCast(::IceProxy::RPCQualityJudge::QualityInf* p) { return p; }

void
::IceProxy::RPCQualityJudge::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RPCQualityJudge::QualityInf>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RPCQualityJudge::QualityInf;
        v->__copyFrom(proxy);
    }
}

::RPCQualityJudge::QualityInfo
IceProxy::RPCQualityJudge::QualityInf::qualitySyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RPCQualityJudge__QualityInf__qualitySyn_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RPCQualityJudge__QualityInf__qualitySyn_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RPCQualityJudge::QualityInf* __del = dynamic_cast< ::IceDelegate::RPCQualityJudge::QualityInf*>(__delBase.get());
            return __del->qualitySyn(inputArgs, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RPCQualityJudge::QualityInf::begin_qualitySyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCQualityJudge__QualityInf__qualitySyn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCQualityJudge__QualityInf__qualitySyn_name, __del, __cookie);
    try
    {
        __result->__prepare(__RPCQualityJudge__QualityInf__qualitySyn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(inputArgs);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::RPCQualityJudge::QualityInfo
IceProxy::RPCQualityJudge::QualityInf::end_qualitySyn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCQualityJudge__QualityInf__qualitySyn_name);
    ::RPCQualityJudge::QualityInfo __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::RPCQualityJudge::QualityInf::qualityAsyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RPCQualityJudge__QualityInf__qualityAsyn_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RPCQualityJudge__QualityInf__qualityAsyn_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RPCQualityJudge::QualityInf* __del = dynamic_cast< ::IceDelegate::RPCQualityJudge::QualityInf*>(__delBase.get());
            return __del->qualityAsyn(inputArgs, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RPCQualityJudge::QualityInf::begin_qualityAsyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCQualityJudge__QualityInf__qualityAsyn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCQualityJudge__QualityInf__qualityAsyn_name, __del, __cookie);
    try
    {
        __result->__prepare(__RPCQualityJudge__QualityInf__qualityAsyn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(inputArgs);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::RPCQualityJudge::QualityInf::end_qualityAsyn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCQualityJudge__QualityInf__qualityAsyn_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::RPCQualityJudge::QualityInfo
IceProxy::RPCQualityJudge::QualityInf::fetchQualityRes(const ::std::string& inputArgs, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RPCQualityJudge__QualityInf__fetchQualityRes_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RPCQualityJudge__QualityInf__fetchQualityRes_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RPCQualityJudge::QualityInf* __del = dynamic_cast< ::IceDelegate::RPCQualityJudge::QualityInf*>(__delBase.get());
            return __del->fetchQualityRes(inputArgs, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RPCQualityJudge::QualityInf::begin_fetchQualityRes(const ::std::string& inputArgs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RPCQualityJudge__QualityInf__fetchQualityRes_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RPCQualityJudge__QualityInf__fetchQualityRes_name, __del, __cookie);
    try
    {
        __result->__prepare(__RPCQualityJudge__QualityInf__fetchQualityRes_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(inputArgs);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::RPCQualityJudge::QualityInfo
IceProxy::RPCQualityJudge::QualityInf::end_fetchQualityRes(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RPCQualityJudge__QualityInf__fetchQualityRes_name);
    ::RPCQualityJudge::QualityInfo __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RPCQualityJudge::QualityInf::ice_staticId()
{
    return ::RPCQualityJudge::QualityInf::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RPCQualityJudge::QualityInf::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RPCQualityJudge::QualityInf);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RPCQualityJudge::QualityInf::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RPCQualityJudge::QualityInf);
}

::IceProxy::Ice::Object*
IceProxy::RPCQualityJudge::QualityInf::__newInstance() const
{
    return new QualityInf;
}

::RPCQualityJudge::QualityInfo
IceDelegateM::RPCQualityJudge::QualityInf::qualitySyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RPCQualityJudge__QualityInf__qualitySyn_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(inputArgs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::RPCQualityJudge::QualityInfo __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::RPCQualityJudge::QualityInf::qualityAsyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RPCQualityJudge__QualityInf__qualityAsyn_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(inputArgs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::RPCQualityJudge::QualityInfo
IceDelegateM::RPCQualityJudge::QualityInf::fetchQualityRes(const ::std::string& inputArgs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RPCQualityJudge__QualityInf__fetchQualityRes_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(inputArgs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::RPCQualityJudge::QualityInfo __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::RPCQualityJudge::QualityInfo
IceDelegateD::RPCQualityJudge::QualityInf::qualitySyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RPCQualityJudge::QualityInfo& __result, const ::RPCQualityJudge::QualityInputStruct& __p_inputArgs, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_inputArgs(__p_inputArgs)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RPCQualityJudge::QualityInf* servant = dynamic_cast< ::RPCQualityJudge::QualityInf*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->qualitySyn(_m_inputArgs, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RPCQualityJudge::QualityInfo& _result;
        const ::RPCQualityJudge::QualityInputStruct& _m_inputArgs;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RPCQualityJudge__QualityInf__qualitySyn_name, ::Ice::Normal, __context);
    ::RPCQualityJudge::QualityInfo __result;
    try
    {
        _DirectI __direct(__result, inputArgs, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::RPCQualityJudge::QualityInf::qualityAsyn(const ::RPCQualityJudge::QualityInputStruct& inputArgs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::RPCQualityJudge::QualityInputStruct& __p_inputArgs, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_inputArgs(__p_inputArgs)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RPCQualityJudge::QualityInf* servant = dynamic_cast< ::RPCQualityJudge::QualityInf*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->qualityAsyn(_m_inputArgs, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
        const ::RPCQualityJudge::QualityInputStruct& _m_inputArgs;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RPCQualityJudge__QualityInf__qualityAsyn_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, inputArgs, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::RPCQualityJudge::QualityInfo
IceDelegateD::RPCQualityJudge::QualityInf::fetchQualityRes(const ::std::string& inputArgs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RPCQualityJudge::QualityInfo& __result, const ::std::string& __p_inputArgs, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_inputArgs(__p_inputArgs)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RPCQualityJudge::QualityInf* servant = dynamic_cast< ::RPCQualityJudge::QualityInf*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->fetchQualityRes(_m_inputArgs, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RPCQualityJudge::QualityInfo& _result;
        const ::std::string& _m_inputArgs;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RPCQualityJudge__QualityInf__fetchQualityRes_name, ::Ice::Normal, __context);
    ::RPCQualityJudge::QualityInfo __result;
    try
    {
        _DirectI __direct(__result, inputArgs, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* RPCQualityJudge::upCast(::RPCQualityJudge::QualityInf* p) { return p; }

namespace
{
const ::std::string __RPCQualityJudge__QualityInf_ids[2] =
{
    "::Ice::Object",
    "::RPCQualityJudge::QualityInf"
};

}

bool
RPCQualityJudge::QualityInf::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RPCQualityJudge__QualityInf_ids, __RPCQualityJudge__QualityInf_ids + 2, _s);
}

::std::vector< ::std::string>
RPCQualityJudge::QualityInf::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RPCQualityJudge__QualityInf_ids[0], &__RPCQualityJudge__QualityInf_ids[2]);
}

const ::std::string&
RPCQualityJudge::QualityInf::ice_id(const ::Ice::Current&) const
{
    return __RPCQualityJudge__QualityInf_ids[1];
}

const ::std::string&
RPCQualityJudge::QualityInf::ice_staticId()
{
    return __RPCQualityJudge__QualityInf_ids[1];
}

::Ice::DispatchStatus
RPCQualityJudge::QualityInf::___qualitySyn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RPCQualityJudge::QualityInputStruct inputArgs;
    __is->read(inputArgs);
    __inS.endReadParams();
    ::RPCQualityJudge::QualityInfo __ret = qualitySyn(inputArgs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RPCQualityJudge::QualityInf::___qualityAsyn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RPCQualityJudge::QualityInputStruct inputArgs;
    __is->read(inputArgs);
    __inS.endReadParams();
    ::Ice::Int __ret = qualityAsyn(inputArgs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RPCQualityJudge::QualityInf::___fetchQualityRes(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string inputArgs;
    __is->read(inputArgs);
    __inS.endReadParams();
    ::RPCQualityJudge::QualityInfo __ret = fetchQualityRes(inputArgs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RPCQualityJudge__QualityInf_all[] =
{
    "fetchQualityRes",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "qualityAsyn",
    "qualitySyn"
};

}

::Ice::DispatchStatus
RPCQualityJudge::QualityInf::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RPCQualityJudge__QualityInf_all, __RPCQualityJudge__QualityInf_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RPCQualityJudge__QualityInf_all)
    {
        case 0:
        {
            return ___fetchQualityRes(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___qualityAsyn(in, current);
        }
        case 6:
        {
            return ___qualitySyn(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RPCQualityJudge::QualityInf::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RPCQualityJudge::QualityInf::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RPCQualityJudge::__patch(QualityInfPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RPCQualityJudge::QualityInfPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RPCQualityJudge::QualityInf::ice_staticId(), v);
    }
}
